Removes mention of only supporting Pageant
gitkraken/gitkraken-client-docs pull request #172
Opened 2023-09-20 17:47 UTC by jkelroy

2023-09-20 18:05 UTC, ianhattendorf commented
> Should we leave this in for now until we fully migrate?

Let's leave it for now, I'm not 100% sure which portions of the SSH config GitKraken will respect. It should respect almost all of it when `Use local SSH agent` is checked, but when using integration/profile keys I'm not sure without thinking about it more.

2023-09-20 18:10 UTC, ianhattendorf approved these changes

2023-09-20 18:11 UTC, ianhattendorf requested changes
Hmm, actually we might need to leave this for now. Clone for example is still on NodeGit only, so will only work with Putty over SSH. Unless that's no longer the case for and we support the built-in SSH for NodeGit as well? @relyss do you know if that's the case?

2023-09-21 09:39 UTC, relyss commented
I've tried cloning an SSH URL with Local agent set up for OpenSSH and it worked fine 👍  
I also confirmed that for Git bundled / scm it's working both for bundled and external OpenSSH (chosen during Git installation), as long as the keys are correctly setup and the agent is running, I'm using the one that comes preinstalled in Windows.

2024-05-14 16:09 UTC, jkelroy commented
Hey @jkelroy, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #172**](https://staging.gitkraken.dev/drafts/83dbac51-8506-4cc7-880c-a3339e974ff2?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/172

You can also review and apply these suggestions [locally on your machine](https://staging.gitkraken.dev/link/drafts/83dbac51-8506-4cc7-880c-a3339e974ff2?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSE9FUGk4NWF6eThIIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://staging.gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://staging.gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

2024-05-14 16:10 UTC, jkelroy commented
Hey @jkelroy, while reviewing your PR, I'd suggest the following code changes:

👉 [**Code Suggestion for #172**](https://gitkraken.dev/drafts/15c7c5db-1e68-496f-82e4-29120008e18a?source=PRComment)
>https://github.com/gitkraken/gitkraken-client-docs/pull/172

You can also review and apply these suggestions [locally on your machine](https://gitkraken.dev/link/drafts/15c7c5db-1e68-496f-82e4-29120008e18a?type=suggested_pr_change&prEntityId=WyJnaXRodWIiLCJwciIsIjEiLCIiLCJQUl9rd0RPSE9FUGk4NWF6eThIIl0=&source=PRComment).

<details><summary>Learn more about GitKraken Code Suggest</summary>

>[Code Suggest](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbS9zb2x1dGlvbnMvY29kZS1zdWdnZXN0P3NvdXJjZT1naXRodWIuY29tJm1lZGl1bT1wcl9jb21tZW50?source=PRSuggest&event=redirectToCodeSuggestPage&provider=github) liberates your code reviews from GitHub's restrictive, comment-only feedback style. As simple as suggesting changes in a Google-doc, provide real code suggestions from where you code, e.g. your IDE, and on anything in your project — not just on the lines of code changed in the PR.

_Join your team on [GitKraken](https://gitkraken.dev/redirect/aHR0cHM6Ly93d3cuZ2l0a3Jha2VuLmNvbT9zb3VyY2U9Z2l0aHViLmNvbSZtZWRpdW09cHJfY29tbWVudA==?source=PRSuggest&event=redirectToIndexPage&provider=github) to speed up PR review._
</details>

2024-07-26 22:49 UTC, jkelroy commented
@ianhattendorf @relyss I believe all remote actions are now using Git Executable correct? If so, can we remove the mention of only supporting Pageant now?

CC @vicenter-gitkraken

2024-08-01 13:57 UTC, ianhattendorf commented
> @ianhattendorf @relyss I believe all remote actions are now using Git Executable correct? If so, can we remove the mention of only supporting Pageant now?
> 
> CC @vicenter-gitkraken

There are still places that use NodeGit for remotes, mostly tied to launchpad, submodules, and remote management IIRC. It's just the most common ones that have been converted.

/cc @julianmesa-gitkraken @AlexaXs to confirm, as they've been working on scoping out the last of the migration recently

2024-08-02 09:23 UTC, AlexaXs commented
> > @ianhattendorf @relyss I believe all remote actions are now using Git Executable correct? If so, can we remove the mention of only supporting Pageant now?
> > CC @vicenter-gitkraken
> 
> There are still places that use NodeGit for remotes, mostly tied to launchpad, submodules, and remote management IIRC. It's just the most common ones that have been converted.
> 
> /cc @julianmesa-gitkraken @AlexaXs to confirm, as they've been working on scoping out the last of the migration recently

True, we are still using NodeGit credentials (See trace in [remaining work to remove NodeGit.Cred](https://gitkraken.atlassian.net/wiki/spaces/ENGR/pages/466452487/NodeGit.Cred) down from `getRemoteOptions`) for some cases as Ian says (submodules, adding first remote of a new local repo, and other cases). What we are not sure about is that NodeGit for remote credentials on Windows only supports `pageant`.

2026-04-24 09:31 UTC, closed without merging