Add WSL Help Center Page
gitkraken/gitkraken-client-docs pull request #99
Opened 2023-01-31 00:10 UTC by trevor-polidore

Install requirements, instructions, and some troubleshooting info related to getting GKC installed within a WSL 2 environment

2023-01-31 22:17 UTC, Axxzilla commented
Once we have it, we should add a screenshot of the red error toast that pops up. We can explain what each option means and the "why" behind them. 

Specifically:
- if they ignore/bypass, we should make it clear that it may work for what they want, but is it unsupported. Some features may behave in unintended ways or simply not function in this mode. 
- for the "open in WSL" option, explain why they need to have GKC installed on both windows and WSL.


Maybe we make another section at the top explaining what WSL/WSL2/WSLg is - and how GitKraken is expected to work in this scenario. Then we can simply link to that explanation in this toast section. 

This explication should be well thought out and complete, as I expect Support will be needing to refer customers or otherwise explain this many times.

2023-02-06 09:50 UTC, vicenter-gitkraken requested changes

2023-02-06 09:50 UTC, vicenter-gitkraken commented on gitkraken-client/windows-subsystem-for-linux.md
> +Microsoft also introduced <a href="https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps"
line break "breaks" the HTML tag

2023-02-06 15:50 UTC, jkelroy commented on gitkraken-client/windows-subsystem-for-linux.md
> +- Most recent Linux version of GitKraken Client
Should state the lowest supported version i.e. 9.1.0+

2023-02-06 22:05 UTC, Axxzilla approved these changes

2023-02-07 15:53 UTC, vicenter-gitkraken approved these changes

2023-02-07 17:36 UTC, merged